# ========== Data Sources ==========
data_sources:
  directories:
    - artifacts/data/Deutsche
    - artifacts/data/English
  links:
    # - https://www.gesetze-im-internet.de/enefg/BJNR1350B0023.html

# ========== Data Directories ==========
directories:
  deutsche_chunks_dict: artifacts/chunks/deutsche
  english_chunks_dict: artifacts/chunks/english

# ========== Data Preprocessing ==========
data_preprocessing:
  chunking:
    chunk_size: 1000 # Characters
    chunk_overlap: 200

# ========== Vector Database (Pinecone) ==========
vector_db:
  active: "pinecone"

  providers:
    pinecone:
      api_key: ${PINECONE_API_KEY}
      environment: "us-east-1"
      index_name: "ecopilot-corpus"
      dimension: 1536
      metric: "cosine"
      cloud: "aws"

    postgresql:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      database: ${POSTGRES_DB}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      table: "ecopilot-corpus"

# ========== Embedding Models ==========
embedding_models:
  name: "text-embedding-ada-002"
  dimensions: 1536
  provider: "openai"
  api_key: ${OPENAI_API_KEY}
  sql_table: "openai_embeddings"
