# ========== Data Sources ==========
data_sources:
  directories:
    - dataset/data/pdfs
  links:
    # - https://www.gesetze-im-internet.de/enefg/BJNR1350B0023.html

# ========== Data Directories ==========
directories:
  chunks_dict: dataset/chunks/

# ========== Data Preprocessing ==========
data_preprocessing:
  chunking:
    chunk_size: 256 # token
    chunk_overlap: 20

# ========== Vector Database (Pinecone) ==========
vector_db:
  active: "postgresql" # [pinecone | postgresql]

  postgresql:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    table: "ecopilot-corpus"

# ========== Azure ==========
azure_var:
  AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
  AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
  AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}

# ========== Embedding Models ==========
embedding_models:
  name: "text-embedding-3-small"
  dimensions: 1536
  provider: "openai"
  api_key: ${OPENAI_API_KEY}
  sql_table: "openai_embeddings"

# ========== Large Language Models ==========
language_models:
  active_model: "GPT" # [GPT | llama3-german]

  models:
    GPT:
      provider: "openai"
      model_name: "gpt-4o"
      api_key: ${OPENAI_API_KEY}
      temperature: 0.7
      max_tokens: 4096
      top_p: 0.9
      frequency_penalty: 0.1

    llama3-german:
      provider: "DiscoResearch"
      model_name: "DiscoResearch/Llama3-DiscoLeo-Instruct-8B-v0.1"
      temperature: 0.7
      max_tokens: 4096
      top_p: 0.9
      frequency_penalty: 0.1

  system_prompt: |
    You are an AI-powered assistant designed to help Small and Medium Enterprises (SMEs) navigate energy efficiency regulations, identify energy-saving opportunities, and optimize their energy consumption. Your goal is to provide accurate, tailored, and actionable advice based on the user's query and the provided context.

    **Instructions:**
    1. Carefully analyze the user's query and the retrieved context (if provided).
    2. If the retrieved context is relevant to the query, use it to provide a detailed and accurate response. If the retrieved context is unrelated to the query, ignore it and respond based on your general knowledge.
    3. Always prioritize clarity, accuracy, and relevance in your responses, and provide correct sources if you are confident.
    4. If the user asks about funding programs, tax incentives, compliance requirements, legal questions, or requests a tailored roadmap for the company, make sure to ask: energy consumption, sectors, taken steps,  Are you considered a SME?
    5. Respond in the same language as the user's query. If the query is in German, reply in German. If the query is in English, reply in English.
    6. If you are not sure about answer indicate that you cannot provide a specific answer.

    Now, proceed with the user's query and the retrieved context (if any).
